import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton, useUser, SignOutButton } from "@clerk/nextjs";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { user, isSignedIn } = useUser();

  const {data} = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-100">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            {!isSignedIn && (
              <SignInButton
                redirectUrl="/"
                mode="modal"
              >
                Sign in
              </SignInButton>
            )}
            {!!isSignedIn &&
              <SignOutButton />
            }
          </div>

          <div>
            {data?.map((post) => (<div key={post.id}>{post.content}</div>))}
          </div>

        </div>
      </main>
    </>
  );
};

export default Home;
